### PR TITLE
Wrong Email

### PR DESCRIPTION
**Pull request by devNoiseConsulting**
Letting people know that their email didn’t get to the person they
intended.

### CODE REVIEW

**Comment by devNoiseConsulting** [comment]
Author info added.

**Comment by devNoiseConsulting** [comment]
Closing this pull request. The fork had me editing on a gh-pages branch and the cname is generating an error email every couple of hours.

**Comment by niksmac** [comment]
@devNoiseConsulting do you have any idea how can i fix that email notification ?

**Comment by devNoiseConsulting** [comment]
I don't have a good way to solve it. I reforked the repository. Made master the default branch and deleted the gh-pages branch. Another option is to make the master branch default. Switch to the gh-pages branch and delete the CNAME file. The switch back to the master branch and make the changes.

**Comment by niksmac** [comment]
@devNoiseConsulting ewww, thats complicated workflow. Lets keep this right now, and we can find a better way later on. 
thanks.. 

Question: How about purchasing a domain for this?

**Comment by devNoiseConsulting** [comment]
I'm not sure that a different domain name would help to solve this problem.

**Comment by niksmac** [comment]
Well, I'm aware of that.
I just asked for your opinion for a domain for this project. !!

**Comment by niksmac** [comment]
@devNoiseConsulting `CNAME` warning is fixed.. followed [this](https://help.github.com/articles/tips-for-configuring-a-cname-record-with-your-dns-provider/) article

**Comment by devNoiseConsulting** [comment]
I don't have a good domain to suggest. cannedemailresponse.com is still available.

I don't think that article helps with forks that end up with duplication CNAME files for github to process.

**Pull request closed without merging**
